---
title: "MATH 4720 (MSSC 5720) Statistical Methods Spring 2026"
tbl-colwidths: [5,8,20,10,6,6,8,6,6,6]
format:
  html
---

*This schedule will be updated as the semester progresses, with all changes documented here.*

::: column-screen-inset-right
| Week | Date | Topic | Materials | Reading | R Code | Homework | Worksheet | Quiz | Exam/Project |
|:------:|--------|--------|:------:|:------:|:------:|:------:|--------|:------:|:------:|
| 1 | Tue, Jan 13 | Syllabus/Overview of Statistics | [🖥️ syllabus](slides/01-syllabus-slides.html)<br>[🖥️ statistics and data](slides/02-overview-slides.html) | [Syllabus](course-syllabus.html)<br>[IS Ch1](https://chenghanyu-introstatsbook.netlify.app/intro-stats)<br>[GenAI Video](https://shorturl.at/0yLUl) |  |  |  |  |  |
|  | Thu, Jan 15 | Statistical Studies and Data Collection; Data Type |  | [IS Ch 2](https://chenghanyu-introstatsbook.netlify.app/intro-data) |  | ✍️ [HW 1 (due 1/23)](hw/hw01.html) |  |  |  |
| 2 | Tue, Jan 20 | R Software and Computation | [🖥️ R and RStudio](/slides/03-r-slides.html)<br>[🖥️ data type and structure](/slides/04-programming-slides.html) | [IS Ch 3](https://chenghanyu-introstatsbook.netlify.app/intro-r) | [`r fontawesome::fa("file-code")`](/code/03_intro-r.R) (data type and structure) |  |  |  |  |
|  | Thu, Jan 22 | Summarizing Data: Tables and Graphics | [🖥️ data summary](/slides/05-data-description-slides.html)<br>👉[histogram breaks](ojs/data-hist-ojs.html)<br>👉[data extremes](ojs/data-extremes-ojs.html) | [IS Ch 5 - 6](https://chenghanyu-introstatsbook.netlify.app/data-graphics) | [`r fontawesome::fa("file-code")`](/code/04_data-graphics.R) (data graphics) |  |  |  |  |
| 3 | Tue, Jan 27 | Summarizing Data: Numerical measures |  |  | [`r fontawesome::fa("file-code")`](/code/04_data-numerics.R) (data numerics) |  |  |  |  |
|  | Thu, Jan 29 | Probability Fundamentals | [🖥️ probability](/slides/06-probability-slides.html)<br>👉[Venn diagram](http://www.stat.ucla.edu/~vlew/stat11/lectures/venn/venn.html) | [IS Ch 7 - 8](https://chenghanyu-introstatsbook.netlify.app/prob-define) |  | ✍️ [HW 2 (due 2/6)](hw/hw02.html) | [Worksheet 1](ws/ws1.html) |  |  |
| 4 | Tue, Feb 3 | Conditional Probability, Independence, Bayes Formula |  |  |  |  | [Worksheet 2](ws/ws2.html) |  |  |
|  | Thu, Feb 5 | Random Variables, Discrete Probability Distributions | [🖥️ distribution](/slides/07-distribution-slides.html) <br>👉[binomial](ojs/prob-binomial-ojs.html)<br>👉[poisson](ojs/prob-poisson-ojs.html) | [IS Ch 9 - 10](https://chenghanyu-introstatsbook.netlify.app/prob-rv) | [`r fontawesome::fa("file-code")`](/code/09-prob-disc.R) (discrete distribution) | ✍️ [HW 3 (due 2/13](hw/hw03.html)✍️[Extra Credit (due 2/13)](hw/hw03-extra.html) |  | ✅ [Quiz 1](/documents/quiz1.pdf) |  |
| 5 | Tue, Feb 10 | Continuous Probability Distributions | 👉[normal](ojs/prob-normal-ojs.html) | [IS Ch 11](https://chenghanyu-introstatsbook.netlify.app/prob-cont) | [`r fontawesome::fa("file-code")`](/code/10-prob-cont.R) (continuous distribution) |  | [Worksheet 3](ws/ws3.html) |  |  |
|  | Thu, Feb 12 | Sampling Distributions [**Activity: Match the Scenario to the Distribution**](/activity/act_distribution.html) | [🖥️ sampling-dist-clt](/slides/08-sampling-dist-clt-slides.html) | [IS Ch 12](https://chenghanyu-introstatsbook.netlify.app/prob-sampling#why-use-sampling-distribution) | [`r fontawesome::fa("file-code")`](/code/11-prob-sampling-clt.R) (sampling distribution and CLT) |  |  |  |  |
| 6 | Tue, Feb 17 | Central Limit Theorem (CLT) | 👉[CLT](ojs/prob-clt-ojs.html)<br> 👉[Rolling dice](https://019b5202-4521-e665-b54e-580b72438130.share.connect.posit.cloud/) | [IS Ch 13](https://chenghanyu-introstatsbook.netlify.app/prob-llnclt#central-limit-theorem) |  |  |  |  |  |
|  | Thu, Feb 19 | Confidence Intervals | [🖥️ confidence interval](/slides/09-ci-slides.html) <br> 👉[CI](ojs/infer-ci-ojs.html) | [IS Ch 14](https://chenghanyu-introstatsbook.netlify.app/infer-ci) | [`r fontawesome::fa("file-code")`](/code/13-infer-ci.R) (confidence interval) | ✍️ [HW 4 (due 2/27)](hw/hw04.html) | [Worksheet 4](ws/ws4.html) |  |  |
| 7 | Tue, Feb 24 | Confidence Intervals | 👉[Student-t](ojs/infer-ci-t-ojs.html) |  |  |  |  |  |  |
|  | Thu, Feb 26 | Exam 1 Review [**Activity:** **How Much Do Students Sleep?**](/activity/act_ci.html) |  |  |  |  | [Worksheet 5](ws/ws5.html) | ✅ [Quiz 2](/documents/quiz2.pdf) | [Exercise 1](exercise/exercise1.html) |
| 8 | Tue, Mar 3 | **In-class Exam 1** |  |  |  |  |  |  | ✅ [Take-home Exam 1](/exam/take_home_exam1.html) |
|  | Thu, Mar 5 | Hypothesis Testing | [🖥️ testing](/slides/10-ht-slides.html)<br> 👉[testing](ojs/infer-ht-ojs.html) | [IS Ch 16](https://chenghanyu-introstatsbook.netlify.app/infer-ht) | [`r fontawesome::fa("file-code")`](/code/15-infer-ht.R) (testing) |  |  |  |  |
| 9 | Tue, Mar 10 | ***NO CLASS: Spring break*** |  |  |  |  |  |  |  |
|  | Thu, Mar 12 | ***NO CLASS: Spring break*** |  |  |  |  |  |  |  |
| 10 | Tue, Mar 17 | Hypothesis Testing |  |  |  |  |  |  |  |
|  | Thu, Mar 19 | Two Population Means: Matched Pairs | 🖥️ two samples | [IS Ch 17](https://chenghanyu-introstatsbook.netlify.app/infer-twomean) | `r fontawesome::fa("file-code")` (two samples) | ✍️ HW 5 (due 3/27) |  |  |  |
| 11 | Tue, Mar 24 | Two Population Means: Independent Samples |  |  |  |  |  |  |  |
|  | Thu, Mar 26 | Inference for One Population Variance | 🖥️ variances <br> 👉chi-squared | [IS Ch 18](https://chenghanyu-introstatsbook.netlify.app/infer-var) | `r fontawesome::fa("file-code")` (variances) | ✍️ HW 6 (due 4/3) |  | ✅ Quiz 3 |  |
| 12 | Tue, Mar 31 | Inference about Two Population Variances | 👉 f |  |  |  |  |  |  |
|  | Thu, Apr 2 | ***NO CLASS: Easter break*** |  |  |  |  |  |  |  |
| 13 | Tue, Apr 7 | Analysis of Variance (ANOVA) Rationale | 🖥️ ANOVA | [IS Ch 24](https://chenghanyu-introstatsbook.netlify.app/model-anova) | `r fontawesome::fa("file-code")` (ANOVA data) |  |  |  |  |
|  | Thu, Apr 9 | Analysis of Variance (ANOVA) Procedure |  |  |  | ✍️ HW 7 (due 4/17) |  |  |  |
| 14 | Tue, Apr 14 | Correlation; Overview of Regression | 🖥️ correlation <br> 🖥️ regression <br> 👉 regression fitting | [IS Ch 27.1](https://chenghanyu-introstatsbook.netlify.app/model-reg#correlation); [IS Ch 27.2](https://chenghanyu-introstatsbook.netlify.app/model-reg#meaning-of-regression) | `r fontawesome::fa("file-code")` (correlation and regression) |  |  |  |  |
|  | Thu, Apr 16 | Simple Linear Regression: Fitting and Inference **Activity: Height vs. Shoe Size** | 👉 sampling distribution of coefficients | [IS Ch 27.3 - 27.5](https://chenghanyu-introstatsbook.netlify.app/model-reg#fitting-a-regression-line-haty-b_0-b_1x) |  |  |  | ✅ Quiz 4 |  |
| 15 | Tue, Apr 21 | **In-class Exam 2** |  |  |  |  |  |  | ✅ Take-home Exam 2 |
|  | Thu, Apr 23 | Simple Linear Regression: Prediction |  | [IS Ch 27.6](https://chenghanyu-introstatsbook.netlify.app/model-reg#prediction) |  | ✍️ HW 8 (due 5/1) |  |  |  |
| 16 | Tue, Apr 28 | To Be Determined |  |  |  |  |  |  | 📂 Final Project Guideline |
|  | Tue, Apr 30 | To Be Determined |  |  |  |  |  |  |  |
| 17 | Fri, May 8 | **Final Project** |  |  |  |  |  |  |  |
:::

Dr. Yu reserves the right to make changes to the schedule.

```{r echo = FALSE}
knitr::knit_exit()
```

|   |   |   | Prepare | Slides | AE | Labs | HW | Exam | Project |
|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Week | Date | Topic | 📖 | 🖥️ | 📋 | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️ | ✅ | 📂 |
